#!/usr/bin/env bash
# Display information about subdomains

# Function to display subdomain information
display_info() {
  subdomain="$1"
  domain="$2"

  dig_result=$(dig "$subdomain.$domain" +short)

  if [ -z "$dig_result" ]; then
    echo "The subdomain $subdomain does not exist."
  else
    record_type=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
    destination=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
  fi
}

# Main script logic
if [ "$#" -eq 1 ]; then
  domain="$1"
  subdomains=("www" "lb-01" "web-01" "web-02")

  for subdomain in "${subdomains[@]}"; do
    display_info "$subdomain" "$domain"
  done
elif [ "$#" -eq 2 ]; then
  domain="$1"
  subdomain="$2"
  display_info "$subdomain" "$domain"
else
  echo "Usage: $0 <domain> [subdomain]"
  exit 1
fi
