#!/usr/bin/env bash
# This script installs and configures HAProxy on Ubuntu

# Update and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo bash -c "cat > /etc/haproxy/haproxy.cfg" <<EOL
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server web-01 [35.175.65.241]-web-01:80 check
    server web-02 [35.175.130.125]-web-02:80 check
EOL

# Ensure HAProxy can be managed via init script
sudo systemctl enable haproxy
sudo systemctl restart haproxy

# Verify HAProxy status
sudo systemctl status haproxy
