#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend ruova.tech.com.ng
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 328587-web-01 35.175.65.241
        server 328587-web-02 35.175.130.125
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
