#!/usr/bin/env bash
# This script displays time in a 12-hour format
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59

hour=0
max_hours=12
max_minutes=59

while [ $hour -le 12 ]
do
echo "Hour: $hour"
minute=1
while [ $minute -le 59 ]
do
	echo "$minute"
(( minute++ ))
	done
(( hour++ ))
	done
