#!/usr/bin/env bash
# This script provides information about the school file.

FILE="school"

if [ -e "$FILE" ];
then
    echo "school file exists"
    
      if [ -s "school" ];
then
        echo "school file is not empty"
        
          if [ -f "school" ];
then
            echo "school is a regular file"
        fi
    else
        echo "school file is empty"
    fi
else
    echo "school file does not exist"
fi
