#!/usr/bin/env bash

# Install nginx and ufw
sudo apt-get update -y
sudo apt-get install nginx ufw -y

# Configure ufw to block all incoming traffic except for specific TCP ports
sudo ufw default deny incoming
sudo ufw allow ssh
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Enable ufw and reload nginx
sudo ufw enable
sudo systemctl reload nginx
