#!/usr/bin/env bash
# Configuring ufw
sudo apt-get update -y
sudo apt-get install nginx ufw -y
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow 'Nginx Full'
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo systemctl reload nginx
