#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine.
# Use ifconfig to get IPv4 addresses
ip_addresses=$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*')
